[toolchain]

[features]
seeds = false
skip-lint = false

[test]
startup_wait = 10000

[programs.localnet]
token_22_staking = "EYZPBAg8e4rTCUsEoavXgywPr2c8JjTDkXx46dVmDeY2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/regular-token-staking.ts"
test-regular-token-staking = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/regular-token-staking.ts"